/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 *      (c) Copyright 2009-2023 SAP SE. All rights reserved
 */
sap.ui.define(["sap/fe/core/buildingBlocks/BuildingBlockBase","sap/fe/core/buildingBlocks/BuildingBlockSupport","sap/fe/core/buildingBlocks/BuildingBlockTemplateProcessor","sap/fe/core/formatters/KPIFormatter","sap/fe/core/helpers/BindingToolkit"],function(e,t,i,r,n){"use strict";var o,a,l,s,u,p,c,f,d,b,g;var m={};var h=n.resolveBindingString;var y=n.pathInModel;var v=n.formatResult;var P=i.xml;var B=t.defineBuildingBlock;var k=t.blockAttribute;function x(e,t,i,r){if(!i)return;Object.defineProperty(e,t,{enumerable:i.enumerable,configurable:i.configurable,writable:i.writable,value:i.initializer?i.initializer.call(r):void 0})}function w(e){if(e===void 0){throw new ReferenceError("this hasn't been initialised - super() hasn't been called")}return e}function z(e,t){e.prototype=Object.create(t.prototype);e.prototype.constructor=e;E(e,t)}function E(e,t){E=Object.setPrototypeOf?Object.setPrototypeOf.bind():function e(t,i){t.__proto__=i;return t};return E(e,t)}function K(e,t,i,r,n){var o={};Object.keys(r).forEach(function(e){o[e]=r[e]});o.enumerable=!!o.enumerable;o.configurable=!!o.configurable;if("value"in o||o.initializer){o.writable=true}o=i.slice().reverse().reduce(function(i,r){return r(e,t,i)||i},o);if(n&&o.initializer!==void 0){o.value=o.initializer?o.initializer.call(n):void 0;o.initializer=undefined}if(o.initializer===void 0){Object.defineProperty(e,t,o);o=null}return o}function $(e,t){throw new Error("Decorating class property failed. Please ensure that "+"proposal-class-properties is enabled and runs after the decorators transform.")}let O=(o=B({name:"AnalyticalKPITag",namespace:"sap.fe.macros"}),a=k({type:"string",required:true}),l=k({type:"sap.ui.model.Context",required:true}),s=k({type:"string",required:true}),u=k({type:"boolean",required:false}),o(p=(c=function(e){z(t,e);function t(){var t;for(var i=arguments.length,r=new Array(i),n=0;n<i;n++){r[n]=arguments[n]}t=e.call(this,...r)||this;x(t,"id",f,w(t));x(t,"metaPath",d,w(t));x(t,"kpiModelName",b,w(t));x(t,"hasUnit",g,w(t));return t}m=t;var i=t.prototype;i.getKpiPropertyExpression=function e(t){return y(`/${this.id}/manifest/sap.card/data/json/${t}`,this.kpiModelName)};i.getBindingExpressions=function e(){const t=this.metaPath.getProperty("Title");if(!t){return{text:undefined,tooltip:undefined}}const i=h(t);return{text:v([i],r.labelFormat),tooltip:v([i,this.getKpiPropertyExpression("mainValueUnscaled"),this.getKpiPropertyExpression("mainUnit"),this.getKpiPropertyExpression("mainCriticality"),String(this.hasUnit)],r.tooltipFormat)}};i.getTemplate=function e(){const{text:t,tooltip:i}=this.getBindingExpressions();return P`<macros:KPITag
			id="kpiTag-${this.id}"
			text="${t}"
			status="${this.getKpiPropertyExpression("mainCriticality")}"
			tooltip="${i}"
			press=".kpiManagement.onKPIPressed(\${$source>},'${this.id}')"
			number="${this.getKpiPropertyExpression("mainValue")}"
			unit="${this.getKpiPropertyExpression("mainUnit")}"
		/>`};return t}(e),f=K(c.prototype,"id",[a],{configurable:true,enumerable:true,writable:true,initializer:null}),d=K(c.prototype,"metaPath",[l],{configurable:true,enumerable:true,writable:true,initializer:null}),b=K(c.prototype,"kpiModelName",[s],{configurable:true,enumerable:true,writable:true,initializer:null}),g=K(c.prototype,"hasUnit",[u],{configurable:true,enumerable:true,writable:true,initializer:null}),c))||p);m=O;return m},false);
//# sourceMappingURL=AnalyticalKPITag.block.js.map